# Generated by Django 3.1.5 on 2021-01-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.CharField(max_length=25, verbose_name='icon'),
        ),
    ]
