# Generated by Django 3.1.5 on 2021-01-16 23:00

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(choices=[('lni-rocket', 'Rocket'), ('lni-cog', 'gear'), ('lni-mobile', 'Mobile'), ('lni-users', 'Users'), ('lni-layers', 'Design'), ('lni-stats-up', 'Graphic')], max_length=15, verbose_name='icon'),
        ),
    ]
