# Generated by Django 3.1.5 on 2021-01-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210116_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Create at')),
                ('modified', models.DateField(auto_now=True, verbose_name='Update at')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('icon', models.CharField(choices=[('lni-cog', 'gear'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Layers'), ('lni-users', 'Users'), ('lni-rocket', 'Rocket'), ('lni-laptop-phone', 'Phone'), ('lni-stats-up', 'Graphic'), ('lni-leaf', 'Leaf'), ('lni-layers', 'Design')], max_length=25, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(choices=[('lni-cog', 'gear'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Layers'), ('lni-users', 'Users'), ('lni-rocket', 'Rocket'), ('lni-laptop-phone', 'Phone'), ('lni-stats-up', 'Graphic'), ('lni-leaf', 'Leaf'), ('lni-layers', 'Design')], max_length=25, verbose_name='icon'),
        ),
    ]
