# Generated by Django 3.1.5 on 2021-01-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210118_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='icon',
        ),
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(default='Graphic', max_length=25, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icon',
            name='value',
            field=models.CharField(default='value', max_length=25, verbose_name='value'),
            preserve_default=False,
        ),
    ]
