# Generated by Django 3.1.5 on 2021-01-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210118_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.CharField(choices=[('lni-stats-up', 'Graphic'), ('lni-layers', 'Design'), ('lni-laptop-phone', 'Phone'), ('lni-leaf', 'Leaf'), ('lni-rocket', 'Rocket'), ('lni-cog', 'gear'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Layers'), ('lni-users', 'Users')], max_length=25, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(choices=[('lni-stats-up', 'Graphic'), ('lni-layers', 'Design'), ('lni-laptop-phone', 'Phone'), ('lni-leaf', 'Leaf'), ('lni-rocket', 'Rocket'), ('lni-cog', 'gear'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Layers'), ('lni-users', 'Users')], max_length=25, verbose_name='icon'),
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
